{
 "title": "2021-05-08-Group-6-Log-Analysis",
 "time": { "from": "2020-09-08T22:51:53.073Z", "to": "2020-09-08T23:00:17.874Z" },
 "panels": [
  {
   "title": "# Threat Bandwith",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT extract(year from p.timestamp) as \"time\", count(i.threat_type_bandwith)\nFROM pfsense_log AS p\nJoin ip4 AS i ON p.id=i.id\nWhere i.threat_type_bandwith='1'\nGROUP BY 1;\n"
    }
   ]
  },
  {
   "title": "# Threat Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT extract(year from p.timestamp) as \"time\", count(i.threat_type_frequency)\r\nFROM pfsense_log AS p\r\nJoin ip4 AS i ON p.id=i.id\r\nWhere i.threat_type_frequency='1'\r\nGROUP BY 1;"
    }
   ]
  },
  {
   "title": "# Threats by Country",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "Select p.timestamp as \"time\", count(i.data_length) as \"value\", i.source_country_code as \"metric\"\nFROM pfsense_log AS p\nJoin ip4 AS i ON p.id=i.id\nWHERE $__timeFilter(p.timestamp)\nAND i.source_country_code IS NOT NULL\nGroup By p.timestamp, i.source_country_code;"
    }
   ]
  },
  {
   "title": "Threats Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "Select p.timestamp as \"time\", count(i.source_ip) as \"value\"\nFROM pfsense_log AS p\nJoin ip4 AS i ON p.id=i.id \nWhere i.threat_type_bandwith='1'\nGroup By p.timestamp\nOrder By p.timestamp;"
    },
    {
     "rawSql": "Select p.timestamp as \"time\", count(i.source_ip) as \"value\"\nFROM pfsense_log AS p\nJoin ip4 AS i ON p.id=i.id \nWhere i.threat_type_frequency='1'\nGroup By p.timestamp\nOrder By p.timestamp;\n"
    }
   ]
  },
  {
   "title": "# Logs Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "Select p.timestamp as \"time\", count(i.source_ip) as \"value\"\nFROM pfsense_log AS p\nJoin ip4 AS i ON p.id=i.id \nGroup By p.timestamp;\n\n"
    }
   ]
  }
 ]
}